// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9fHOa-qLiG95uQzhqyTluPKSCA6U3h8',
    appId: '1:1007229911565:web:2a1adc66072cd622164b44',
    messagingSenderId: '1007229911565',
    projectId: 'my-unix-app-17-d8a63',
    authDomain: 'my-unix-app-17-d8a63.firebaseapp.com',
    storageBucket: 'my-unix-app-17-d8a63.firebasestorage.app',
    measurementId: 'G-YS7NSHSVT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3fPL3Jf3mNg_jFIDpuBqk_8cOmz3R_I',
    appId: '1:1007229911565:android:45743dc7e291e6b7164b44',
    messagingSenderId: '1007229911565',
    projectId: 'my-unix-app-17-d8a63',
    storageBucket: 'my-unix-app-17-d8a63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9rMmDByHAz_Udd2lvjCB9Q6-6ZufW-WE',
    appId: '1:1007229911565:ios:60b3e15b6005098b164b44',
    messagingSenderId: '1007229911565',
    projectId: 'my-unix-app-17-d8a63',
    storageBucket: 'my-unix-app-17-d8a63.firebasestorage.app',
    iosBundleId: 'com.unix.app.unixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9rMmDByHAz_Udd2lvjCB9Q6-6ZufW-WE',
    appId: '1:1007229911565:ios:60b3e15b6005098b164b44',
    messagingSenderId: '1007229911565',
    projectId: 'my-unix-app-17-d8a63',
    storageBucket: 'my-unix-app-17-d8a63.firebasestorage.app',
    iosBundleId: 'com.unix.app.unixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN9fHOa-qLiG95uQzhqyTluPKSCA6U3h8',
    appId: '1:1007229911565:web:a01499b1e6f4c05e164b44',
    messagingSenderId: '1007229911565',
    projectId: 'my-unix-app-17-d8a63',
    authDomain: 'my-unix-app-17-d8a63.firebaseapp.com',
    storageBucket: 'my-unix-app-17-d8a63.firebasestorage.app',
    measurementId: 'G-NG0YM7DQS9',
  );
}
